
ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - grafana.example.com

hostAliases: 
  - ip: "1.2.3.4"
    hostnames:
      - "prometheus.local.com"
  # annotations:
  #   kubernetes.io/ingress.class: nginx
    # cert-manager.io/cluster-issuer: letsencrypt-prod
  # tls:
  #   - secretName: grafana-tls
  #     hosts:
  #       - grafana.example.com
