objstoreConfig:
  type: s3
  config:
    bucket: my-thanos-bucket
    endpoint: s3.amazonaws.com
    access_key: my-access-key
    secret_key: my-secret-key

query:
  enabled: true
  replicaCount: 2

storeGateway:
  enabled: true
  replicaCount: 2
  persistence:
    enabled: true
    size: 10Gi

compactor:
  enabled: true
  retentionResolutionRaw: 30d
  retentionResolution5m: 180d
  retentionResolution1h: 1y
  persistence:
    enabled: true
    size: 20Gi
